version: '3.8'

networks:
  fastapi_todo_app-network:
    driver: bridge

services:
  fastapi_app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    #ports:
     # - "8000:8000"
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql://postgres:piter@pg:5432/TodoApplicationDatabase
    restart: unless-stopped
    networks:
      - fastapi_todo_app-network

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: piter
      POSTGRES_DB: TodoApplicationDatabase
    ports:
      - "5432:5432"
    volumes:
      - ./Volume-Database:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fastapi_todo_app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
    restart: unless-stopped
    networks:
      - fastapi_todo_app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pg
    restart: unless-stopped
    networks:
      - fastapi_todo_app-network
